# jumlah_pohon = int(input ("jumlah pohon "))
# print(f"arry hutomo tanam {jumlah_pohon} pohon!")
# jumlah_pohon = int(input ("jumlah pohon yang ditanam "))
# print(f"arry hutomo tanam {jumlah_pohon} pohon!")
# berat_sampah = float(input("masukan berat sampah yang didaur ulang Arry Hutomo (kg) "))
# print(f"Arry Hutomo daur ulang {berat_sampah} kg sampah!")
# komunitas = input( "masukan nama komunitas Arry Hutomo: " )
# print(f"Arry Hutomo bareng {komunitas} bantu anak putus sekolah!")
# donasi = int(input("masukkan jumlah donasi Arry Hutomo (Rp) :"))
# print(f"Arry Hutomo donasi Rp {donasi} buat UMKM!")
# pohon_tanam = int(input("masukkan jumlah pohon yang ditanam Arry Hutomo: "))
# pohon_tambah = int(input("masukkan jumlah pohon tambahan: "))
# total = pohon_tanam + pohon_tambah
# print(f"Arry Hutomo tanam {total} pohon!")
# sampah_awal = float(input("masukkan berat sampah awal (kg): "))
# sampah_daur = float(input("masukkan berat sampah yang didaur ulang: "))
# sisa = sampah_awal - sampah_daur
# print(f"Arry Hutomo kurangi sampah jadi {sisa} kg!")
# lampu = int(input("masukkan jumlah lampu per rumah: "))
# rumah = int(input("masukkan jumlah rumah: "))
# total_lampu = lampu * rumah
# print(f"Arry Hutomo hemat {total_lampu} lampu!")
# donasi = int(input(" masukkan total donasi Arry Hutomo (Rp): "))
# penerima = int(input("masukkan jumlas penerima: "))
# per_orang = donasi / penerima
# print(f"Arry Hutomo bagi Rp {per_orang} per orang!")
# pohon = int(input("masukkan jumlah pohon yang ditanam: "))
# print(f"Arry Hutomo tanam {pohon} pohon!\nayo ikut!")
# sampah = float(input("masukkan berat sampah (kg): "))
# nama = input( "masukkan nama: " )
# print("Arry Hutomo daur ulang", sampah, "kg bareng", nama, sep=" - ")
# lampu = int(input("masukkan jumlah lampu: "))
# print(f"Arry Hutomo hemat {lampu} lampu ", end="")
# print("di rumah!")
# pohon = int(input("masukkan jumlah pohon awal: "))
# tambah = int(input("masukkan jumlah pohon tambah: "))
# mati = int(input("masukkan jumlah pohon mati: "))
# total = (pohon + tambah - mati) / 2 
# print(f"Arry Hutomo rata rata {total} pohon!")
# donasi = int(input("masukkan total donasi (Rp): "))
# penerima = int(input("masukkan jumlah penerima: "))
# sisa = donasi % penerima
# print(f"Arry Hutomo punya sisa Rp {sisa}!")
# lampu = int(input("masukkan jumlah lampu: "))
# rumah = int(input("masukkan jumlah rumah: "))
# bagi = lampu // rumah
# print(f"Arry Hutomo bagi {bagi} lampu per rumah!\nayo hemat!")
sampah = float(input("masukkan jumlah sampah awal (kg): "))
daur = float(input("masukkan jumlah sampah yang didaur ulang (kg): "))
tambah = float(input("masukkan sampah tambahan (kg): "))
hasil = (sampah - daur + tambah) * 2 / 3
print(f"Arru Hutomo hitung sampah {hasil} kg!\nlakukan ", f"lagi bareng EEC Team!", sep="=>", end="")
print("yuk!")